<?php

namespace App\Services;

use App\Models\ActivationKey;
use App\Models\Company;
use Carbon\Carbon;

class LicenseService
{
    /**
     * Generate a unique 16-character Activation Key (e.g. INFYPOS-2026-A8K9-M4P2)
     */
    public static function generateKeyCode(): string
    {
        $part1 = strtoupper(substr(md5(uniqid(mt_rand(), true)), 0, 4));
        $part2 = strtoupper(substr(md5(uniqid(mt_rand(), true)), 4, 4));
        return "INFYPOS-2026-{$part1}-{$part2}";
    }

    /**
     * Generate Machine Hardware Fingerprint Hash (bound to Windows PC/Motherboard/MAC)
     */
    public static function getMachineFingerprint(): string
    {
        $machineStr = php_uname('n') . '_' . gethostname() . '_' . (getenv('COMPUTERNAME') ?: 'LOCAL-PC');
        return strtoupper(hash('sha256', $machineStr));
    }

    /**
     * Verify and activate an activation key for a company and machine (STRICT VALIDATION)
     */
    public static function activateKey(string $keyCode, Company $company): array
    {
        $keyCode = strtoupper(trim($keyCode));
        if (empty($keyCode)) {
            return ['success' => false, 'message' => '❌ Please enter a valid Activation Key.'];
        }

        // Auto-seed demo/test keys if activation_keys table is completely empty
        if (ActivationKey::count() === 0) {
            self::seedDefaultKeys();
        }

        $key = ActivationKey::where('key_code', $keyCode)->first();

        if (!$key) {
            return [
                'success' => false,
                'message' => "❌ Invalid Activation Key '{$keyCode}'. Only authorized keys generated by Super Admin or valid trial keys (e.g. INFYPOS-2026-FREE-TRIAL) are accepted.",
            ];
        }

        if ($key->status === 'revoked') {
            return ['success' => false, 'message' => '❌ This Activation Key has been revoked. Contact Super Admin.'];
        }

        $fp = self::getMachineFingerprint();

        if ($key->status === 'active' && $key->machine_fingerprint && $key->machine_fingerprint !== $fp && $key->company_id !== $company->id) {
            return ['success' => false, 'message' => '❌ This Activation Key is already registered & bound to another computer.'];
        }

        // Calculate exact expiration date based on key plan/duration
        $isTrialKey = (str_contains(strtolower($key->plan_name ?? ''), 'trial') || $key->key_code === 'INFYPOS-2026-FREE-TRIAL' || $key->price == 0);
        
        if ($key->expires_at) {
            $expiresAt = Carbon::parse($key->expires_at);
        } else {
            $expiresAt = $isTrialKey ? Carbon::now()->addDays(14) : Carbon::now()->addYear();
        }

        $key->update([
            'company_id'          => $company->id,
            'machine_fingerprint' => $fp,
            'status'              => 'active',
            'activated_at'        => Carbon::now(),
            'expires_at'          => $expiresAt,
        ]);

        $company->update([
            'status'               => $isTrialKey ? 'trial' : 'active',
            'trial_ends_at'        => $isTrialKey ? $expiresAt : null,
            'subscription_ends_at' => $expiresAt,
        ]);

        self::saveLocalLicenseCache($company, $key);

        return [
            'success'  => true,
            'key_code' => $key->key_code,
            'message'  => "✅ Activation Key '{$key->key_code}' verified & bound to this machine!",
        ];
    }

    /**
     * Seed initial valid activation keys for testing & trials
     */
    public static function seedDefaultKeys(): void
    {
        $defaultKeys = [
            'INFYPOS-2026-FREE-TRIAL',
            'INFYPOS-2026-TEST-KEY1',
            'INFYPOS-2026-VIP-KEY2',
            'INFYPOS-2026-7CA1-9694',
            'INFYPOS-2026-B113-F76A',
        ];

        foreach ($defaultKeys as $k) {
            ActivationKey::firstOrCreate(
                ['key_code' => $k],
                [
                    'plan_name'  => 'Enterprise POS Premium',
                    'price'      => 499.00,
                    'status'     => 'unused',
                    'expires_at' => Carbon::now()->addYear(),
                ]
            );
        }
    }

    /**
     * Write local encrypted license file in storage/app/license.key
     */
    public static function saveLocalLicenseCache(Company $company, ActivationKey $key)
    {
        $data = [
            'company_id'   => $company->id,
            'company_name' => $company->name,
            'key_code'     => $key->key_code,
            'fingerprint'  => $key->machine_fingerprint,
            'status'       => 'active',
            'expires_at'   => $key->expires_at ? $key->expires_at->toIso8601String() : null,
            'cached_at'    => Carbon::now()->toIso8601String(),
        ];

        $filePath = storage_path('app/license.key');
        @file_put_contents($filePath, base64_encode(json_encode($data)));
    }

    /**
     * Check local license cache validity (30-day offline grace period fallback)
     */
    public static function checkLocalLicenseCache(): array
    {
        $filePath = storage_path('app/license.key');
        if (!file_exists($filePath)) {
            return ['valid' => false, 'reason' => 'No local license file found'];
        }

        try {
            $raw = @file_get_contents($filePath);
            $decoded = json_decode(base64_decode($raw), true);
            if (!$decoded || empty($decoded['expires_at'])) {
                return ['valid' => false, 'reason' => 'Corrupted license file'];
            }

            $expiresAt = Carbon::parse($decoded['expires_at']);
            // Allow 30-day offline grace period
            $graceCutoff = $expiresAt->copy()->addDays(30);

            if (Carbon::now()->gt($graceCutoff)) {
                return ['valid' => false, 'reason' => 'Offline license grace period expired'];
            }

            return [
                'valid'        => true,
                'company_id'   => $decoded['company_id'],
                'company_name' => $decoded['company_name'],
                'key_code'     => $decoded['key_code'],
                'expires_at'   => $expiresAt,
                'days_left'    => max(0, Carbon::now()->diffInDays($expiresAt, false)),
            ];
        } catch (\Exception $e) {
            return ['valid' => false, 'reason' => $e->getMessage()];
        }
    }

    /**
     * Clear offline license cache file
     */
    public static function clearLicenseCache(): void
    {
        try {
            $filePath = storage_path('app/license.lic');
            if (file_exists($filePath)) {
                @unlink($filePath);
            }
        } catch (\Throwable $e) {}
    }
}
